from pathlib import Path
p=Path('app/api/accounting/reports/route.ts')
s=p.read_text()
old="""      const lineProfit = lineSales - lineCogs\n      const salePerPc = qty ? lineSales / qty : 0\n      const profitPerPc = salePerPc - lineCost\n      calculatedInvoiceCogs += lineCogs\n      invoiceLines.push({ product_id: item.product_id, name: productName, sku, quantity: qty, cost_per_pc: round2(lineCost), sale_per_pc: round2(salePerPc), profit_per_pc: round2(profitPerPc), total_sales: round2(lineSales), total_cost: round2(lineCogs), total_profit: round2(lineProfit) })\n      const lineCogs = qty * lineCost"""
# Handle the actual generated order: lineCogs is before lineProfit, but the push was inserted before productName.
old2="""      const lineProfit = lineSales - lineCogs\n      const salePerPc = qty ? lineSales / qty : 0\n      const profitPerPc = salePerPc - lineCost\n      calculatedInvoiceCogs += lineCogs\n      invoiceLines.push({ product_id: item.product_id, name: productName, sku, quantity: qty, cost_per_pc: round2(lineCost), sale_per_pc: round2(salePerPc), profit_per_pc: round2(profitPerPc), total_sales: round2(lineSales), total_cost: round2(lineCogs), total_profit: round2(lineProfit) })\n      const meta = productMeta.get(item.product_id)\n      const productName = item.product_name || meta?.name || 'Unknown product'\n      const sku = item.sku ?? meta?.sku ?? null"""
new2="""      const lineProfit = lineSales - lineCogs\n      const salePerPc = qty ? lineSales / qty : 0\n      const profitPerPc = salePerPc - lineCost\n      calculatedInvoiceCogs += lineCogs\n      const meta = productMeta.get(item.product_id)\n      const productName = item.product_name || meta?.name || 'Unknown product'\n      const sku = item.sku ?? meta?.sku ?? null\n      invoiceLines.push({ product_id: item.product_id, name: productName, sku, quantity: qty, cost_per_pc: round2(lineCost), sale_per_pc: round2(salePerPc), profit_per_pc: round2(profitPerPc), total_sales: round2(lineSales), total_cost: round2(lineCogs), total_profit: round2(lineProfit) })"""
if old2 not in s:
    raise SystemExit('expected generated sequence not found')
p.write_text(s.replace(old2,new2))
