'use client'

import { useEffect, useState } from 'react'
import { CreditCard, Loader2 } from 'lucide-react'
import toast from 'react-hot-toast'

type Payment={id:string;receipt_no:string;payment_method:string;amount:number;reference_no:string|null;paid_at:string;invoice_id:string;parties?:{name:string}|null;sales_invoices?:{invoice_no:string;grand_total:number}|null}
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
export default function PaymentsPage(){const [rows,setRows]=useState<Payment[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{fetch('/api/payments').then(async r=>{const j=await r.json();if(!r.ok)toast.error(j.error||'Unable to load payments');else setRows(j.payments||[]);setLoading(false)}).catch(()=>{toast.error('Unable to load payments');setLoading(false)})},[]);const total=rows.reduce((n,x)=>n+Number(x.amount||0),0);return <div className="mx-auto max-w-7xl space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><CreditCard className="h-6 w-6"/></span><div><span className="text-xs font-semibold uppercase tracking-wide text-blue-600">Phase 9 · Accounts</span><h1 className="mt-1 text-2xl font-bold">Payments</h1><p className="mt-1 text-sm text-slate-500">Central register of customer payments received against sales invoices.</p></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Payment Register</h2><p className="text-xs text-slate-500">{rows.length} receipts · Active payments</p></div><p className="text-2xl font-bold">{money(total)}</p></div>{loading?<div className="py-16 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-blue-600"/></div>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="p-3">Date</th><th className="p-3">Receipt</th><th className="p-3">Customer</th><th className="p-3">Invoice</th><th className="p-3">Method</th><th className="p-3 text-right">Amount</th></tr></thead><tbody className="divide-y">{rows.map(x=><tr key={x.id}><td className="p-3 text-slate-500">{new Date(x.paid_at).toLocaleString('en-IN')}</td><td className="p-3 font-semibold">{x.receipt_no}</td><td className="p-3">{x.parties?.name||'Walk-in'}</td><td className="p-3">{x.sales_invoices?.invoice_no||'—'}</td><td className="p-3 capitalize">{x.payment_method}</td><td className="p-3 text-right font-bold">{money(x.amount)}</td></tr>)}</tbody></table></div>}</section></div>}
