'use client'

import { useEffect, useState } from 'react'
import { Loader2, Printer, ReceiptText } from 'lucide-react'
import toast from 'react-hot-toast'

type Payment={id:string;receipt_no:string;payment_method:string;amount:number;reference_no:string|null;paid_at:string;invoice_id:string;parties?:{name:string}|null;sales_invoices?:{invoice_no:string;grand_total:number}|null}
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
export default function ReceiptsPage(){const [rows,setRows]=useState<Payment[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{fetch('/api/payments').then(async r=>{const j=await r.json();if(!r.ok)toast.error(j.error||'Unable to load receipts');else setRows(j.payments||[]);setLoading(false)}).catch(()=>{toast.error('Unable to load receipts');setLoading(false)})},[]);return <div className="mx-auto max-w-6xl space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><ReceiptText className="h-6 w-6"/></span><div><span className="text-xs font-semibold uppercase tracking-wide text-blue-600">Phase 9 · Accounts</span><h1 className="mt-1 text-2xl font-bold">Receipts</h1><p className="mt-1 text-sm text-slate-500">Print-ready receipt register generated from recorded customer payments.</p></div></div></section>{loading?<div className="rounded-2xl border bg-white p-16 text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-blue-600"/></div>:<div className="grid gap-4 md:grid-cols-2">{rows.map(x=><article key={x.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm print:shadow-none"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase text-slate-400">Payment Receipt</p><h2 className="mt-1 text-xl font-bold">{x.receipt_no}</h2></div><button onClick={()=>window.print()} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-xs font-semibold hover:bg-slate-50"><Printer className="h-4 w-4"/> Print</button></div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Customer</span><b>{x.parties?.name||'Walk-in customer'}</b></div><div className="flex justify-between"><span className="text-slate-500">Invoice</span><b>{x.sales_invoices?.invoice_no||'—'}</b></div><div className="flex justify-between"><span className="text-slate-500">Payment method</span><b className="capitalize">{x.payment_method}</b></div><div className="flex justify-between"><span className="text-slate-500">Reference</span><b>{x.reference_no||'—'}</b></div><div className="border-t pt-3 flex justify-between text-lg"><span>Received</span><b>{money(x.amount)}</b></div><p className="text-xs text-slate-400">{new Date(x.paid_at).toLocaleString('en-IN')}</p></div></article>)}</div>}</div>}
