'use client'

import { useEffect, useMemo, useState } from 'react'
import { BarChart3, BookOpen, CalendarDays, Download, FileText, Loader2, RefreshCw, TrendingDown, TrendingUp, WalletCards } from 'lucide-react'
import toast from 'react-hot-toast'

type Report = {
  period:{start:string;end:string}
  summary:{income:number;expense:number;sales:number;purchases:number;costOfGoodsSold:number;grossProfit:number;netProfit:number;assets:number;liabilities:number;equity:number;debtors:number;creditors:number;cash:number;bank:number;stock:number;trialDebit:number;trialCredit:number}
  trialBalance:{id:string;name:string;code:string|null;nature:string;group:string;debit:number;credit:number;balance:number;balance_type:string}[]
  pnlAccounts:{name:string;nature:string;group:string;debit:number;credit:number;balance:number}[]
  balanceSheet:{name:string;nature:string;group:string;debit:number;credit:number;balance:number}[]
  aging:{name:string;party_id:string;type:string;amount:number}[]
  topExpenses:{name:string;amount:number}[]
}
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const pct=(n:number)=>`${Number(n||0).toFixed(1)}%`

export default function AnalysisPage(){
 const [data,setData]=useState<Report|null>(null); const [loading,setLoading]=useState(true); const [tab,setTab]=useState<'pnl'|'balance'|'trial'|'parties'|'ratios'>('pnl');
 const today=new Date().toISOString().slice(0,10); const fyStart=new Date(new Date().getMonth()<3?new Date().getFullYear()-1:new Date().getFullYear(),3,1).toISOString().slice(0,10)
 const [start,setStart]=useState(fyStart); const [end,setEnd]=useState(today)
 async function load(){setLoading(true);try{const r=await fetch(`/api/accounting/reports?start=${start}&end=${end}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}catch(e){toast.error(e instanceof Error?e.message:'Unable to load accounting reports')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const pnl=useMemo(()=>{if(!data)return {income:[],expense:[]};return {income:data.pnlAccounts.filter(x=>x.nature==='income').sort((a,b)=>(b.credit-b.debit)-(a.credit-a.debit)),expense:data.pnlAccounts.filter(x=>x.nature==='expense').sort((a,b)=>(b.debit-b.credit)-(a.debit-a.credit))}},[data])
 function exportCsv(){if(!data)return;const rows=[['BIZBook Accounting Report',`${data.period.start} to ${data.period.end}`],[],['P&L','Amount'],['Sales',data.summary.sales],['Cost of Goods Sold',data.summary.costOfGoodsSold],['Gross Profit',data.summary.grossProfit],['Other Income',data.summary.income-data.summary.sales],['Operating Expenses',data.summary.expense],['Net Profit / Loss',data.summary.netProfit],[],['Inventory Purchases (Balance Sheet / Stock)',data.summary.purchases],[],['Balance Sheet','Amount'],['Assets',data.summary.assets],['Liabilities',data.summary.liabilities],['Equity incl. current profit',data.summary.equity],[],['Receivables',data.summary.debtors],['Payables',data.summary.creditors],['Cash',data.summary.cash],['Bank',data.summary.bank],['Stock',data.summary.stock]];const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([`\uFEFF${csv}`],{type:'text/csv'}));a.download=`accounting-report-${data.period.start}-to-${data.period.end}.csv`;a.click();URL.revokeObjectURL(a.href);toast.success('Report exported')}
 if(loading)return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-indigo-600"/></div>
 if(!data)return null
 const s=data.summary; const grossMargin=s.sales?Math.max(-999,Math.min(999,s.grossProfit/s.sales*100)):0; const netMargin=s.sales?s.netProfit/s.sales*100:0; const currentRatio=s.liabilities?s.assets/s.liabilities:0; const debtRatio=s.assets?(s.liabilities/s.assets)*100:0
 return <div className="mx-auto max-w-[1500px] space-y-5">
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex rounded-full bg-indigo-100 px-3 py-1 text-xs font-bold text-indigo-700">ADMIN · ACCOUNTING CONTROL CENTRE</span><h1 className="mt-3 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">Financial Analysis & Reports</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-500">BUSY-style management reporting with correct inventory accounting: purchases build stock, while only the cost of goods actually sold enters Profit & Loss.</p></div><div className="flex flex-wrap gap-2"><input type="date" value={start} onChange={e=>setStart(e.target.value)} className="min-h-10 rounded-xl border px-3 text-sm"/><input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="min-h-10 rounded-xl border px-3 text-sm"/><button onClick={()=>void load()} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white"><CalendarDays className="h-4 w-4"/>Apply</button><button onClick={exportCsv} className="inline-flex min-h-10 items-center gap-2 rounded-xl border px-4 text-sm font-bold"><Download className="h-4 w-4"/>Export</button><button onClick={()=>void load()} className="inline-flex min-h-10 items-center gap-2 rounded-xl border px-3"><RefreshCw className="h-4 w-4"/></button></div></div></section>

  <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{[[TrendingUp,'Sales',s.sales],[BookOpen,'Gross Profit',s.grossProfit],[TrendingDown,'Expenses',s.expense],[WalletCards,'Net Profit',s.netProfit],[WalletCards,'Receivables',s.debtors],[WalletCards,'Payables',s.creditors],[WalletCards,'Cash + Bank',s.cash+s.bank],[BookOpen,'Stock',s.stock]].map(([I,label,value])=>{const Icon=I as typeof TrendingUp;return <div key={String(label)} className="rounded-2xl border bg-white p-4 shadow-sm"><Icon className="h-4 w-4 text-indigo-600"/><p className="mt-2 text-[10px] font-bold uppercase tracking-wide text-slate-400">{String(label)}</p><p className={`mt-1 text-lg font-black ${String(label).includes('Profit')&&Number(value)<0?'text-red-600':''}`}>{money(Number(value))}</p></div>})}</section>

  <div className="flex flex-wrap gap-2 rounded-2xl border bg-white p-2 shadow-sm">{[['pnl','Profit & Loss'],['balance','Balance Sheet'],['trial','Trial Balance'],['parties','Debtors / Creditors'],['ratios','Ratios & KPIs']].map(([id,label])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={`rounded-xl px-4 py-2.5 text-sm font-bold ${tab===id?'bg-indigo-600 text-white':'text-slate-600 hover:bg-slate-50'}`}>{label}</button>)}</div>

  {tab==='pnl'&&<div className="grid gap-5 lg:grid-cols-[1fr_1fr_360px]"><ReportCard title="Profit & Loss — Income"><ReportTable rows={pnl.income.map(x=>({name:x.name,amount:x.credit-x.debit}))}/><Total label="Total Income" value={s.income}/></ReportCard><ReportCard title="Profit & Loss — Operating Expenses"><ReportTable rows={pnl.expense.map(x=>({name:x.name,amount:x.debit-x.credit}))}/><Total label="Operating Expenses" value={s.expense}/></ReportCard><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black">P&L Summary</h2><div className="mt-4 space-y-3"><Metric label="Sales" value={s.sales}/><Metric label="Cost of Goods Sold" value={-s.costOfGoodsSold}/><Metric label="Gross Profit" value={s.grossProfit}/><Metric label="Other Income" value={s.income-s.sales}/><Metric label="Operating Expenses" value={-s.expense}/><div className="border-t pt-3"><Metric label="NET PROFIT / LOSS" value={s.netProfit} strong/></div></div><div className="mt-5 rounded-xl bg-amber-50 p-4 text-sm"><p className="font-bold text-amber-900">Inventory accounting</p><p className="mt-1 text-amber-800">Purchases of ₹{Number(s.purchases||0).toLocaleString('en-IN',{maximumFractionDigits:0})} are inventory, not an immediate P&L expense. They remain in stock until sold.</p></div><div className="mt-3 rounded-xl bg-slate-50 p-4 text-sm"><p className="font-bold">Margins</p><div className="mt-2 flex justify-between"><span>Gross margin</span><b>{pct(grossMargin)}</b></div><div className="mt-1 flex justify-between"><span>Net margin</span><b>{pct(netMargin)}</b></div></div></section></div>}

  {tab==='balance'&&<div className="grid gap-5 lg:grid-cols-2"><ReportCard title="Assets"><ReportTable rows={data.balanceSheet.filter(x=>x.nature==='asset').map(x=>({name:x.name,amount:x.debit-x.credit}))}/><Total label="Total Assets" value={s.assets}/></ReportCard><ReportCard title="Liabilities & Equity"><ReportTable rows={data.balanceSheet.filter(x=>x.nature==='liability').map(x=>({name:x.name,amount:x.credit-x.debit}))}/><ReportTable rows={data.balanceSheet.filter(x=>x.nature==='equity').map(x=>({name:x.name,amount:x.credit-x.debit}))}/><Total label="Liabilities" value={s.liabilities}/><Total label="Equity + Current Profit" value={s.equity}/></ReportCard></div>}

  {tab==='trial'&&<section className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="font-black">Trial Balance</h2><p className="mt-1 text-xs text-slate-500">Every ledger account with its net debit/credit position.</p></div><div className="overflow-x-auto"><table className="min-w-[900px] w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th className="p-3">Account</th><th className="p-3">Group</th><th className="p-3">Nature</th><th className="p-3 text-right">Debit</th><th className="p-3 text-right">Credit</th></tr></thead><tbody className="divide-y">{data.trialBalance.map(x=><tr key={x.id}><td className="p-3 font-bold">{x.name}</td><td className="p-3 text-slate-500">{x.group}</td><td className="p-3 capitalize">{x.nature}</td><td className="p-3 text-right font-semibold">{x.debit?money(x.debit):'—'}</td><td className="p-3 text-right font-semibold">{x.credit?money(x.credit):'—'}</td></tr>)}</tbody><tfoot className="border-t bg-slate-50 font-black"><tr><td className="p-3" colSpan={3}>TOTAL</td><td className="p-3 text-right">{money(s.trialDebit)}</td><td className="p-3 text-right">{money(s.trialCredit)}</td></tr></tfoot></table></div></section>}

  {tab==='parties'&&<div className="grid gap-5 lg:grid-cols-2"><ReportCard title="Receivables — Sundry Debtors"><PartyTable rows={data.aging.filter(x=>x.type==='receivable')}/><Total label="Total Receivables" value={s.debtors}/></ReportCard><ReportCard title="Payables — Sundry Creditors"><PartyTable rows={data.aging.filter(x=>x.type==='payable')}/><Total label="Total Payables" value={s.creditors}/></ReportCard></div>}

  {tab==='ratios'&&<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Kpi title="Gross Margin" value={pct(grossMargin)} hint="Gross profit / sales"/><Kpi title="Net Margin" value={pct(netMargin)} hint="Net profit / sales"/><Kpi title="Current Ratio" value={currentRatio.toFixed(2)} hint="Assets / liabilities"/><Kpi title="Debt to Asset" value={pct(debtRatio)} hint="Liabilities / assets"/><Kpi title="Receivable to Sales" value={s.sales?pct(s.debtors/s.sales*100):'0.0%'} hint="Working-capital exposure"/><Kpi title="Payable to Purchases" value={s.purchases?pct(s.creditors/s.purchases*100):'0.0%'} hint="Supplier exposure"/><Kpi title="Cash + Bank" value={money(s.cash+s.bank)} hint="Liquid funds"/><Kpi title="Balance Check" value={Math.abs(s.trialDebit-s.trialCredit)<0.01?'OK':'ERROR'} hint="Trial debit must equal credit"/></div>}

  <section className="grid gap-5 lg:grid-cols-2"><ReportCard title="Top Expense Ledgers"><ReportTable rows={data.topExpenses}/></ReportCard><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="font-black">Accounting controls</h2><ul className="mt-4 space-y-2 text-sm text-slate-600"><li>✓ Double-entry journals are generated for sales, purchases, receipts and expenses.</li><li>✓ Purchases are inventory transactions; only sold inventory cost is recognized in P&L.</li><li>✓ Parties are linked to Sundry Debtors / Sundry Creditors ledgers.</li><li>✓ Trial Balance must balance before relying on P&L and Balance Sheet.</li><li>✓ Cash and Bank are separated for management control.</li><li>✓ Opening balances are included through the opening journal.</li><li>✓ Reports can be filtered by financial period and exported.</li></ul></section></section>
 </div>
}
function ReportCard({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-indigo-600"/><h2 className="font-black">{title}</h2></div><div className="mt-4">{children}</div></section>}
function ReportTable({rows}:{rows:{name:string;amount:number}[]}){return <div className="divide-y rounded-xl border">{rows.length?rows.map((x,i)=><div key={`${x.name}-${i}`} className="flex justify-between gap-4 px-3 py-2.5 text-sm"><span className="truncate">{x.name}</span><b>{money(x.amount)}</b></div>):<p className="p-5 text-sm text-slate-400">No entries.</p>}</div>}
function PartyTable({rows}:{rows:{name:string;amount:number}[]}){return <ReportTable rows={rows.map(x=>({name:x.name,amount:x.amount}))}/>} 
function Total({label,value}:{label:string;value:number}){return <div className="mt-3 flex justify-between border-t pt-3 font-black"><span>{label}</span><span>{money(value)}</span></div>}
function Metric({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className={`flex justify-between gap-4 ${strong?'text-lg font-black':''}`}><span>{label}</span><b className={value<0?'text-red-600':''}>{money(value)}</b></div>}
function Kpi({title,value,hint}:{title:string;value:string;hint:string}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{title}</p><p className="mt-2 text-2xl font-black">{value}</p><p className="mt-1 text-xs text-slate-500">{hint}</p></section>}
