'use client'

import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Loader2, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import toast from 'react-hot-toast'

type Product={id:string;name:string;sku:string;purchase_price:number;current_stock:number}
type Party={id:string;name:string;party_type:string}
type Line={product_id:string;quantity:number;unit_price:number}
type Purchase={id:string;invoice_no:string;status:string;grand_total:number;created_at:string;party?:{name:string}|null}
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`

export default function PurchasesPage(){
 const [products,setProducts]=useState<Product[]>([]),[suppliers,setSuppliers]=useState<Party[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]),[supplier,setSupplier]=useState(''),[product,setProduct]=useState(''),[qty,setQty]=useState(1),[price,setPrice]=useState(0),[lines,setLines]=useState<Line[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 const selected=useMemo(()=>products.find(p=>p.id===product),[products,product])
 async function load(){setLoading(true);try{const [c,p,r]=await Promise.all([fetch('/api/catalog?entity=products'),fetch('/api/parties'),fetch('/api/purchases')]);const cj=await c.json(),pj=await p.json(),rj=await r.json();if(!c.ok)throw new Error(cj.error);if(!p.ok)throw new Error(pj.error);if(!r.ok)throw new Error(rj.error);setProducts(cj.products||[]);setSuppliers((pj.parties||[]).filter((x:Party)=>x.party_type==='supplier'||x.party_type==='both'));setPurchases(rj.purchases||[])}catch(e){toast.error(e instanceof Error?e.message:'Unable to load purchases')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 function addLine(){if(!product||qty<=0)return toast.error('Select a product and quantity');setLines(v=>[...v.filter(x=>x.product_id!==product),{product_id:product,quantity:qty,unit_price:price||Number(selected?.purchase_price||0)}]);setProduct('');setQty(1);setPrice(0)}
 async function save(){if(!lines.length)return toast.error('Add at least one product');setSaving(true);try{const r=await fetch('/api/purchases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({party_id:supplier,items:lines})});const j=await r.json();if(!r.ok)throw new Error(j.error);const id=j.purchase?.id;const c=await fetch('/api/purchases',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action:'complete'})});const cj=await c.json();if(!c.ok)throw new Error(cj.error);toast.success('Purchase completed and stock updated');setLines([]);setSupplier('');await load()}catch(e){toast.error(e instanceof Error?e.message:'Unable to save purchase')}finally{setSaving(false)}}
 const total=lines.reduce((n,l)=>n+l.quantity*l.unit_price,0)
 return <div className="mx-auto max-w-7xl space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex items-start gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><ShoppingBag className="h-6 w-6"/></span><div><span className="text-xs font-semibold uppercase tracking-wide text-blue-600">Phase 8 · Purchasing & Inventory</span><h1 className="mt-1 text-2xl font-bold">Purchases</h1><p className="mt-1 text-sm text-slate-500">Record supplier purchases. Completing a purchase increases product stock and creates an audit movement.</p></div></div></section>
 <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">New Purchase</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-medium">Supplier<select value={supplier} onChange={e=>setSupplier(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-3"><option value="">Walk-in / no supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="text-sm font-medium">Product<select value={product} onChange={e=>{setProduct(e.target.value);const p=products.find(x=>x.id===e.target.value);setPrice(Number(p?.purchase_price||0))}} className="mt-1 w-full rounded-xl border border-slate-200 p-3"><option value="">Select product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.sku}</option>)}</select></label><label className="text-sm font-medium">Quantity<input type="number" min="0.001" step="0.001" value={qty} onChange={e=>setQty(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-200 p-3"/></label><label className="text-sm font-medium">Unit price<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-slate-200 p-3"/></label></div><button onClick={addLine} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-blue-200 px-4 py-2.5 text-sm font-semibold text-blue-700 hover:bg-blue-50"><Plus className="h-4 w-4"/> Add line</button>{lines.length>0&&<div className="mt-5 divide-y rounded-xl border">{lines.map(l=>{const p=products.find(x=>x.id===l.product_id);return <div key={l.product_id} className="flex items-center gap-3 p-3 text-sm"><div className="min-w-0 flex-1"><p className="font-semibold">{p?.name}</p><p className="text-xs text-slate-500">{l.quantity} × {money(l.unit_price)}</p></div><span className="font-semibold">{money(l.quantity*l.unit_price)}</span><button onClick={()=>setLines(v=>v.filter(x=>x.product_id!==l.product_id))} className="text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div>})}<div className="flex justify-between p-3 font-bold">Total <span>{money(total)}</span></div></div>}<button disabled={saving||!lines.length} onClick={()=>void save()} className="mt-4 w-full rounded-xl bg-blue-600 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?<Loader2 className="mx-auto h-5 w-5 animate-spin"/>:'Complete Purchase'}</button></div>
 <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Recent Purchases</h2>{loading?<div className="py-12 text-center"><Loader2 className="mx-auto h-6 w-6 animate-spin text-blue-600"/></div>:<div className="mt-4 divide-y">{purchases.length===0?<p className="py-8 text-center text-sm text-slate-500">No purchases yet.</p>:purchases.map(p=><div key={p.id} className="flex items-center gap-3 py-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-slate-50"><CheckCircle2 className="h-4 w-4 text-green-600"/></div><div className="min-w-0 flex-1"><p className="font-semibold">{p.invoice_no}</p><p className="truncate text-xs text-slate-500">{p.party?.name||'No supplier'} · {new Date(p.created_at).toLocaleDateString('en-IN')}</p></div><div className="text-right"><p className="font-semibold">{money(p.grand_total)}</p><p className="text-[10px] uppercase text-green-600">{p.status}</p></div></div>)}</div>}</div></section></div>
}
