import { NextResponse } from 'next/server'
import { z } from 'zod'
import { createClient } from '@/lib/supabase/server'

const schema=z.object({type:z.enum(['sale','purchase']),id:z.string().uuid(),action:z.enum(['cancel','delete','edit']),reason:z.string().trim().max(500).optional(),notes:z.string().trim().max(1500).optional()})
async function context(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{supabase,user:null,profile:null};const {data:profile}=await supabase.from('profiles').select('id,business_id,role,is_active').eq('id',user.id).maybeSingle();return{supabase,user,profile}}
export async function GET(){const {supabase,user,profile}=await context();if(!user||!profile?.is_active||!profile.business_id)return NextResponse.json({error:'Unauthorized'},{status:401});const [sales,purchases]=await Promise.all([supabase.from('sales_invoices').select('id,invoice_no,status,grand_total,created_at,party_id,notes,deleted_at').eq('business_id',profile.business_id).is('deleted_at',null).order('created_at',{ascending:false}).limit(100),supabase.from('purchase_invoices').select('id,invoice_no,status,grand_total,created_at,party_id,notes,deleted_at').eq('business_id',profile.business_id).is('deleted_at',null).order('created_at',{ascending:false}).limit(100)]);if(sales.error||purchases.error)return NextResponse.json({error:sales.error?.message||purchases.error?.message},{status:400});return NextResponse.json({sales:sales.data||[],purchases:purchases.data||[],role:profile.role})}
export async function POST(request:Request){const {supabase,user,profile}=await context();if(!user||!profile?.is_active||!profile.business_id)return NextResponse.json({error:'Unauthorized'},{status:401});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||'Invalid action'},{status:400});const p=parsed.data;
 if(p.action==='delete'){const fn=p.type==='sale'?'soft_delete_sale_invoice':'soft_delete_purchase_invoice';const {data,error}=await supabase.rpc(fn,p.type==='sale'?{p_invoice_id:p.id,p_reason:p.reason||null}:{p_invoice_id:p.id,p_reason:p.reason||null});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({entry:data})}
 if(p.action==='cancel'){const fn=p.type==='sale'?'cancel_sale_invoice':'cancel_purchase_invoice';const {data,error}=await supabase.rpc(fn,p.type==='sale'?{p_invoice_id:p.id,p_reason:p.reason||null}:{p_invoice_id:p.id,p_reason:p.reason||null});if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({entry:data})}
 const table=p.type==='sale'?'sales_invoices':'purchase_invoices';const required=p.type==='sale'?'sales.edit':'purchase.edit';const {data:has}=await supabase.rpc('has_permission',{permission_code:required});if(!has)return NextResponse.json({error:`${required} permission required`},{status:403});const {data:existing,error:findError}=await supabase.from(table).select('id,status,business_id').eq('id',p.id).eq('business_id',profile.business_id).maybeSingle();if(findError||!existing)return NextResponse.json({error:'Entry not found'},{status:404});if(existing.status!=='draft')return NextResponse.json({error:'Only draft entries can be edited safely.'},{status:400});const {data,error}=await supabase.from(table).update({notes:p.notes??null,updated_at:new Date().toISOString()}).eq('id',p.id).eq('business_id',profile.business_id).select().single();if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({entry:data})}
