'use client'
import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, Lightbulb, Send } from 'lucide-react'
import toast from 'react-hot-toast'

export default function FeedbackPage(){
 const [form,setForm]=useState({name:'',role:'Shop owner / staff',phone:'',subject:'',message:''}); const [busy,setBusy]=useState(false)
 const set=(key:string,value:string)=>setForm(x=>({...x,[key]:value}))
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.error);toast.success('Your suggestion has been submitted.');setForm(x=>({...x,subject:'',message:''}))}catch(e){toast.error(e instanceof Error?e.message:'Unable to submit')}finally{setBusy(false)}}
 return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6"><div className="mx-auto max-w-2xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Back to BIZBook</Link><section className="mt-5 overflow-hidden rounded-[30px] bg-gradient-to-br from-indigo-600 via-violet-600 to-fuchsia-600 p-6 text-white shadow-xl sm:p-8"><Lightbulb className="h-9 w-9"/><h1 className="mt-4 text-3xl font-black">Suggestions & Help</h1><p className="mt-2 text-sm leading-6 text-indigo-100">Tell the BIZBook team what you need, report a problem, or ask a question. Your message is submitted as a support request — not sent through WhatsApp.</p><div className="mt-5 rounded-2xl bg-white/10 p-4 text-sm ring-1 ring-white/15">Support contact: <strong>+91-9996609399</strong></div></section><form onSubmit={submit} className="mt-5 space-y-4 rounded-[30px] border bg-white p-5 shadow-sm sm:p-7"><label className="block text-sm font-bold">Your name<input required value={form.name} onChange={e=>set('name',e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border px-3"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-bold">You are<select value={form.role} onChange={e=>set('role',e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border bg-white px-3"><option>Shop owner / staff</option><option>Customer / user</option><option>Other</option></select></label><label className="block text-sm font-bold">Phone (optional)<input value={form.phone} onChange={e=>set('phone',e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border px-3"/></label></div><label className="block text-sm font-bold">Subject<input required value={form.subject} onChange={e=>set('subject',e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border px-3"/></label><label className="block text-sm font-bold">Suggestion or question<textarea required minLength={5} value={form.message} onChange={e=>set('message',e.target.value)} rows={7} className="mt-1.5 w-full rounded-xl border px-3 py-3"/></label><button disabled={busy} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 text-sm font-black text-white disabled:opacity-50"><Send className="h-4 w-4"/>{busy?'Submitting…':'Submit to BIZBook Support'}</button></form></div></main>
}
