'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, ChevronDown, Lightbulb, MessageSquare, Send } from 'lucide-react'
import toast from 'react-hot-toast'

type Submission={id:string;subject:string;message:string;status:string;admin_reply:string|null;created_at:string;updated_at:string}
type Msg={id:string;sender_role:string;body:string;created_at:string}

export default function FeedbackPage(){
 const [form,setForm]=useState({name:'',role:'Shop owner / staff',phone:'',subject:'',message:''}); const [busy,setBusy]=useState(false); const [submissions,setSubmissions]=useState<Submission[]>([]); const [open,setOpen]=useState<string|null>(null); const [messages,setMessages]=useState<Record<string,Msg[]>>({}); const [reply,setReply]=useState(''); const [sending,setSending]=useState(false)
 const set=(key:string,value:string)=>setForm(x=>({...x,[key]:value}))
 async function load(){const r=await fetch('/api/feedback',{cache:'no-store'}); if(r.ok){const d=await r.json();setSubmissions(d.submissions||[])}}
 useEffect(()=>{void load()},[])
 async function openThread(id:string){setOpen(v=>v===id?null:id); if(messages[id])return; const r=await fetch(`/api/feedback/messages?feedback_id=${id}`,{cache:'no-store'}); if(r.ok){const d=await r.json();setMessages(v=>({...v,[id]:d.messages||[]}))}}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.error);toast.success('Your request has been sent to the Super Admin.');setForm(x=>({...x,subject:'',message:''}));await load()}catch(e){toast.error(e instanceof Error?e.message:'Unable to submit')}finally{setBusy(false)}}
 async function sendReply(id:string){if(!reply.trim())return;setSending(true);try{const r=await fetch('/api/feedback/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({feedback_id:id,body:reply})});const d=await r.json();if(!r.ok)throw Error(d.error);setReply('');const m=await fetch(`/api/feedback/messages?feedback_id=${id}`,{cache:'no-store'});const md=await m.json();setMessages(v=>({...v,[id]:md.messages||[]}));await load();toast.success('Reply sent.')}catch(e){toast.error(e instanceof Error?e.message:'Unable to send reply')}finally{setSending(false)}}
 return <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6"><div className="mx-auto max-w-3xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-slate-600"><ArrowLeft className="h-4 w-4"/>Back to BIZBook</Link><section className="mt-5 overflow-hidden rounded-[30px] bg-gradient-to-br from-indigo-600 via-violet-600 to-fuchsia-600 p-6 text-white shadow-xl sm:p-8"><Lightbulb className="h-9 w-9"/><h1 className="mt-4 text-3xl font-black">Suggestions & Improvements</h1><p className="mt-2 text-sm leading-6 text-indigo-100">Send ideas, problem reports or questions directly to the BIZBook Super Admin. Replies stay inside BIZBook — no WhatsApp handoff.</p><div className="mt-5 rounded-2xl bg-white/10 p-4 text-sm ring-1 ring-white/15"><strong>Super Admin Support Desk</strong><br/><span className="text-indigo-100">Secure form routing and in-app two-way conversation.</span></div></section>
 <form onSubmit={submit} className="mt-5 space-y-4 rounded-[30px] border bg-white p-5 shadow-sm sm:p-7"><div className="rounded-2xl bg-indigo-50 p-4 text-sm text-indigo-900">Your request is delivered to the Super Admin support queue and can receive a reply here.</div><label className="block text-sm font-bold">Your name<input required value={form.name} onChange={e=>set('name',e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border px-3"/></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-bold">You are<select value={form.role} onChange={e=>set('role',e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border bg-white px-3"><option>Shop owner / staff</option><option>Customer / user</option><option>Other</option></select></label><label className="block text-sm font-bold">Phone (optional)<input value={form.phone} onChange={e=>set('phone',e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border px-3"/></label></div><label className="block text-sm font-bold">Subject<input required value={form.subject} onChange={e=>set('subject',e.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border px-3"/></label><label className="block text-sm font-bold">Suggestion, improvement or question<textarea required minLength={5} value={form.message} onChange={e=>set('message',e.target.value)} rows={7} className="mt-1.5 w-full rounded-xl border px-3 py-3"/></label><button disabled={busy} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 text-sm font-black text-white disabled:opacity-50"><Send className="h-4 w-4"/>{busy?'Sending…':'Send to Super Admin'}</button></form>
 <section className="mt-6 rounded-[30px] border bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-2"><MessageSquare className="h-5 w-5 text-indigo-600"/><h2 className="text-xl font-black">Your support conversations</h2></div><p className="mt-1 text-sm text-slate-500">Replies from the Super Admin appear here.</p><div className="mt-5 space-y-3">{submissions.map(s=><div key={s.id} className="overflow-hidden rounded-2xl border border-slate-200"><button type="button" onClick={()=>void openThread(s.id)} className="flex w-full items-center gap-3 p-4 text-left hover:bg-slate-50"><span className="min-w-0 flex-1"><span className="block truncate font-bold text-slate-900">{s.subject}</span><span className="mt-1 block text-xs text-slate-500">{new Date(s.created_at).toLocaleString('en-IN')} · {s.status}</span></span><ChevronDown className={`h-5 w-5 transition ${open===s.id?'rotate-180':''}`}/></button>{open===s.id&&<div className="border-t bg-slate-50 p-4"><div className="space-y-3">{(messages[s.id]||[]).length===0&&<div className="rounded-xl bg-white p-4 text-sm text-slate-600"><b>You:</b> {s.message}</div>}{(messages[s.id]||[]).map(m=><div key={m.id} className={`rounded-xl p-4 text-sm ${m.sender_role==='customer'?'bg-white text-slate-700':'bg-indigo-50 text-indigo-950'}`}><div className="mb-1 text-[10px] font-black uppercase tracking-wide opacity-60">{m.sender_role==='customer'?'You':'BIZBook Super Admin'}</div>{m.body}</div>)}<div className="flex gap-2"><input value={open===s.id?reply:''} onChange={e=>setReply(e.target.value)} placeholder="Write a reply…" className="min-h-11 flex-1 rounded-xl border bg-white px-3 text-sm"/><button disabled={sending} onClick={()=>void sendReply(s.id)} className="rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white disabled:opacity-50">Reply</button></div></div></div>}</div>)}{!submissions.length&&<div className="rounded-2xl border-2 border-dashed p-8 text-center text-sm text-slate-500">No previous conversations yet.</div>}</div></section></div></main>
}
