'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Check, Loader2, Minus, Plus, RefreshCw, Search, ShoppingCart, Trash2, UserRound, X, Pause, CreditCard } from 'lucide-react'
import toast from 'react-hot-toast'
import PaymentDialog from './PaymentDialog'

type Product={id:string;sku:string;barcode:string|null;name:string;sale_price:number;current_stock:number;reorder_level:number}
type Party={id:string;party_code:string;name:string;phone:string|null;alternate_phone?:string|null;party_type:'customer'|'supplier'|'both'}
type CartItem=Product&{quantity:number;unit_price:number;pricing_source:'base'|'price_list';price_overridden:boolean}
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}`

export default function SalesPage(){
 const [products,setProducts]=useState<Product[]>([]),[parties,setParties]=useState<Party[]>([]),[cart,setCart]=useState<CartItem[]>([]),[productSearch,setProductSearch]=useState(''),[partySearch,setPartySearch]=useState(''),[customer,setCustomer]=useState(''),[showProducts,setShowProducts]=useState(false),[showParties,setShowParties]=useState(false),[productLoading,setProductLoading]=useState(false),[partyLoading,setPartyLoading]=useState(false),[saving,setSaving]=useState(false),[paymentInvoiceId,setPaymentInvoiceId]=useState<string|null>(null),[paymentOpen,setPaymentOpen]=useState(false),[mobileCart,setMobileCart]=useState(false)
 const productInput=useRef<HTMLInputElement>(null)
 async function searchProducts(q:string){setProductLoading(true);try{const r=await fetch(`/api/pos/products?q=${encodeURIComponent(q)}&limit=30`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setProducts(d.products||[])}catch(e){toast.error(e instanceof Error?e.message:'Unable to search products')}finally{setProductLoading(false)}}
 async function searchParties(q:string){setPartyLoading(true);try{const r=await fetch(`/api/pos/parties?q=${encodeURIComponent(q)}&limit=30`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setParties((d.parties||[]).filter((p:Party)=>p.party_type==='customer'||p.party_type==='both'))}catch(e){toast.error(e instanceof Error?e.message:'Unable to search customers')}finally{setPartyLoading(false)}}
 async function load(){await Promise.all([searchProducts(''),searchParties('')])}
 useEffect(()=>{void load()},[]);useEffect(()=>{const t=setTimeout(()=>void searchProducts(productSearch),220);return()=>clearTimeout(t)},[productSearch]);useEffect(()=>{const t=setTimeout(()=>void searchParties(partySearch),220);return()=>clearTimeout(t)},[partySearch]);useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName||'')){e.preventDefault();productInput.current?.focus();setShowProducts(true)}if(e.key==='Escape'){setShowProducts(false);setShowParties(false)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[])
 const subtotal=useMemo(()=>cart.reduce((s,i)=>s+i.quantity*Number(i.unit_price),0),[cart]),selectedCustomer=parties.find(p=>p.id===customer),itemCount=cart.reduce((s,i)=>s+i.quantity,0)
 async function price(productId:string,quantity:number){const p=new URLSearchParams({product_id:productId,quantity:String(quantity)});if(customer)p.set('customer_id',customer);const r=await fetch(`/api/pos/pricing?${p}`,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);return{unit_price:Number(d.unit_price),pricing_source:d.source as CartItem['pricing_source']}}
 async function addProduct(p:Product){try{const old=cart.find(i=>i.id===p.id),qty=(old?.quantity||0)+1;if(old?.price_overridden)setCart(c=>c.map(i=>i.id===p.id?{...i,quantity:i.quantity+1}:i));else{const pr=await price(p.id,qty);setCart(c=>{const f=c.find(i=>i.id===p.id);return f?c.map(i=>i.id===p.id?{...i,quantity:i.quantity+1,unit_price:pr.unit_price,pricing_source:pr.pricing_source}:i):[...c,{...p,quantity:1,unit_price:pr.unit_price,pricing_source:pr.pricing_source,price_overridden:false}]})}setProductSearch('');setShowProducts(false);requestAnimationFrame(()=>productInput.current?.focus())}catch(e){toast.error(e instanceof Error?e.message:'Unable to add product')}}
 async function qty(id:string,n:number){if(n<=0)return setCart(c=>c.filter(i=>i.id!==id));const old=cart.find(i=>i.id===id);if(old?.price_overridden)return setCart(c=>c.map(i=>i.id===id?{...i,quantity:n}:i));try{const p=await price(id,n);setCart(c=>c.map(i=>i.id===id?{...i,quantity:n,unit_price:p.unit_price,pricing_source:p.pricing_source}:i))}catch(e){toast.error(e instanceof Error?e.message:'Unable to update quantity')}}
 function setPrice(id:string,v:string){const n=Number(v);if(!Number.isFinite(n)||n<0)return;setCart(c=>c.map(i=>i.id===id?{...i,unit_price:n,price_overridden:true}:i))}
 async function save(status:'draft'|'completed'){if(!cart.length)return toast.error('Add at least one product');setSaving(true);try{const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:{party_id:customer||null,status,items:cart.map(i=>({product_id:i.id,quantity:i.quantity,unit_price:i.unit_price,discount_amount:0}))}})}),d=await r.json();if(!r.ok)throw Error(d.error);setCart([]);setCustomer('');setPartySearch('');if(status==='draft')toast.success('Draft saved');else{toast.success('Invoice saved');setPaymentInvoiceId(d.invoice.id);setPaymentOpen(true)}}catch(e){toast.error(e instanceof Error?e.message:'Unable to save sale')}finally{setSaving(false)}}
 return <div className="mx-auto max-w-[1550px] pb-28 lg:pb-8">
  <header className="mb-4 overflow-hidden rounded-[28px] bg-gradient-to-r from-indigo-700 via-violet-600 to-fuchsia-600 p-5 text-white shadow-lg sm:p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex gap-3"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white/15 ring-1 ring-white/20"><ShoppingCart/></span><div><p className="text-xs font-black uppercase tracking-[.2em] text-indigo-100">Sales / Invoice (POS)</p><h1 className="mt-1 text-2xl font-black sm:text-3xl">Fast Billing</h1><p className="mt-1 text-sm text-indigo-100">Busy-style billing with live stock, fast search and quick payment.</p></div></div><div className="flex gap-2"><span className="hidden rounded-xl bg-white/10 px-3 py-2 text-xs sm:block">Press <b>/</b> to search</span><button onClick={()=>void load()} className="min-h-11 rounded-xl bg-white/10 px-4 text-sm font-bold ring-1 ring-white/20"><RefreshCw className="mr-2 inline h-4 w-4"/>Refresh</button></div></div></header>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_410px]">
   <main className="min-w-0 space-y-4">
    <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-4 lg:grid-cols-[.9fr_1.4fr]">
     <div className="relative"><label className="mb-2 block text-xs font-black uppercase tracking-wide text-slate-500">Customer / Party</label><div className="flex min-h-12 items-center gap-2 rounded-2xl border border-slate-200 px-3 focus-within:border-indigo-500 focus-within:ring-4 focus-within:ring-indigo-50"><UserRound className="text-slate-400"/><input value={selectedCustomer?.name||partySearch} onChange={e=>{setCustomer('');setPartySearch(e.target.value);setShowParties(true)}} onFocus={()=>setShowParties(true)} placeholder="Walk-in customer — search name / mobile" className="min-w-0 flex-1 outline-none"/>{partyLoading&&<Loader2 className="animate-spin text-indigo-600"/>}{customer&&<button onClick={()=>{setCustomer('');setPartySearch('')}}><X className="text-slate-400"/></button>}</div>{showParties&&!customer&&<div className="absolute left-0 right-0 top-[78px] z-40 max-h-72 overflow-y-auto rounded-2xl border bg-white shadow-2xl">{parties.slice(0,12).map(p=><button key={p.id} onMouseDown={e=>e.preventDefault()} onClick={()=>{setCustomer(p.id);setShowParties(false)}} className="flex w-full gap-3 border-b p-3 text-left hover:bg-indigo-50"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 text-xs font-bold">{p.name.slice(0,2).toUpperCase()}</span><span><b className="block text-sm">{p.name}</b><small className="text-slate-500">{p.party_code} · {p.phone||'No mobile'}</small></span></button>)}{!parties.length&&<div className="p-5 text-center text-sm text-slate-500">No customer found</div>}</div>}</div>
     <div className="relative"><label className="mb-2 block text-xs font-black uppercase tracking-wide text-slate-500">Add Product</label><div className="flex min-h-12 items-center gap-2 rounded-2xl border border-slate-200 px-3 focus-within:border-indigo-500 focus-within:ring-4 focus-within:ring-indigo-50"><Search className="text-slate-400"/><input ref={productInput} value={productSearch} onChange={e=>{setProductSearch(e.target.value);setShowProducts(true)}} onFocus={()=>setShowProducts(true)} placeholder="Search name, SKU or barcode…" className="min-w-0 flex-1 outline-none"/>{productLoading&&<Loader2 className="animate-spin text-indigo-600"/>}<span className="hidden rounded-lg bg-slate-100 px-2 py-1 text-[10px] sm:block">/</span></div>{showProducts&&<div className="absolute left-0 right-0 top-[78px] z-40 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="max-h-[55vh] overflow-y-auto">{products.slice(0,12).map(p=><button key={p.id} onMouseDown={e=>e.preventDefault()} onClick={()=>void addProduct(p)} className="flex w-full items-center gap-3 border-b border-slate-100 px-4 py-3 text-left hover:bg-indigo-50"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-indigo-50 text-xs font-black text-indigo-600">{p.name.slice(0,2).toUpperCase()}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{p.name}</b><small className="block truncate text-slate-500">{p.sku} · Stock {p.current_stock}</small></span><b className="text-sm">{money(p.sale_price)}</b><Plus className="h-5 w-5 text-indigo-600"/></button>)}{!products.length&&<div className="p-7 text-center text-sm text-slate-500">{productSearch?'No matching product':'Type a name, SKU or barcode'}</div>}</div></div>}</div>
    </div></section>
    <section className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b p-4 sm:p-5"><div><h2 className="font-black">Invoice Items <span className="ml-1 rounded-full bg-indigo-50 px-2 py-1 text-xs text-indigo-700">{itemCount}</span></h2><p className="text-xs text-slate-500">Edit quantity and rate directly · live stock shown</p></div><div className="flex gap-2"><button onClick={()=>setCart([])} disabled={!cart.length} className="rounded-xl border border-rose-100 px-3 py-2 text-xs font-bold text-rose-600 disabled:opacity-40"><Trash2 className="mr-1 inline h-4 w-4"/>Clear</button><button className="hidden rounded-xl border px-3 py-2 text-xs font-bold sm:inline-flex"><Pause className="mr-1 h-4 w-4"/>Hold</button></div></div>{cart.length?<div className="overflow-x-auto"><table className="min-w-[850px] w-full text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3 text-left"># Product</th><th className="px-3 py-3 text-left">Stock</th><th className="px-3 py-3">Qty</th><th className="px-3 py-3 text-right">Rate</th><th className="px-3 py-3 text-right">Amount</th><th/></tr></thead><tbody className="divide-y divide-slate-100">{cart.map((i,n)=><tr key={i.id}><td className="px-4 py-4"><div className="font-bold">{n+1}. {i.name}</div><div className="text-xs text-slate-500">{i.sku}</div></td><td className="px-3 py-4"><span className={i.current_stock<=i.reorder_level?'text-amber-600':'text-emerald-600'}>{i.current_stock}</span></td><td className="px-3 py-4"><div className="mx-auto flex w-fit items-center rounded-xl border"><button onClick={()=>void qty(i.id,i.quantity-1)} className="p-2"><Minus className="h-4 w-4"/></button><b className="min-w-8 text-center">{i.quantity}</b><button onClick={()=>void qty(i.id,i.quantity+1)} className="p-2"><Plus className="h-4 w-4"/></button></div></td><td className="px-3 py-4"><input type="number" value={i.unit_price} onChange={e=>setPrice(i.id,e.target.value)} className="w-28 rounded-xl border px-3 py-2 text-right font-semibold outline-none focus:border-indigo-500"/></td><td className="px-3 py-4 text-right font-black">{money(i.quantity*i.unit_price)}</td><td className="px-3"><button onClick={()=>void qty(i.id,0)} className="text-rose-500"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div>:<div className="p-14 text-center sm:p-20"><ShoppingCart className="mx-auto h-12 w-12 text-slate-200"/><h3 className="mt-3 font-bold text-slate-600">No items added</h3><p className="mt-1 text-sm text-slate-400">Search above or scan a barcode to start billing.</p><button onClick={()=>productInput.current?.focus()} className="mt-5 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">Add first product</button></div>}</section>
   </main>
   <aside className="hidden xl:block"><div className="sticky top-4 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl"><div className="bg-gradient-to-br from-indigo-700 to-violet-600 p-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-indigo-100">Bill Summary</p><p className="mt-1 text-4xl font-black">{money(subtotal)}</p><p className="mt-1 text-sm text-indigo-100">{itemCount} items · {selectedCustomer?.name||'Walk-in Customer'}</p></div><div className="space-y-3 p-5"><div className="flex justify-between text-sm"><span className="text-slate-500">Subtotal</span><b>{money(subtotal)}</b></div><div className="flex justify-between border-t pt-3 text-lg"><span className="font-bold">Net Amount</span><b className="text-indigo-700">{money(subtotal)}</b></div><button disabled={saving||!cart.length} onClick={()=>void save('completed')} className="min-h-14 w-full rounded-2xl bg-emerald-500 text-base font-black text-white shadow-lg shadow-emerald-100 disabled:opacity-40"><Check className="mr-2 inline h-5 w-5"/>Save & Receive Payment</button><button disabled={saving||!cart.length} onClick={()=>void save('draft')} className="min-h-12 w-full rounded-2xl border border-slate-200 text-sm font-bold disabled:opacity-40">Save as Draft</button></div></div></aside>
  </div>
  <div className="fixed bottom-3 left-3 right-3 z-30 xl:hidden"><div className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-white/95 p-2 shadow-2xl backdrop-blur"><button onClick={()=>setMobileCart(true)} className="min-h-12 flex-1 rounded-xl bg-slate-100 px-3 text-left"><span className="block text-xs font-bold text-slate-500">{itemCount} items</span><b>{money(subtotal)}</b></button><button disabled={saving||!cart.length} onClick={()=>void save('completed')} className="min-h-12 flex-[1.4] rounded-xl bg-emerald-500 px-3 text-sm font-black text-white disabled:opacity-40"><CreditCard className="mr-1 inline h-4 w-4"/>Pay / Save</button></div></div>
  {mobileCart&&<div className="fixed inset-0 z-50 bg-slate-950/50 xl:hidden"><div className="absolute inset-x-0 bottom-0 max-h-[85vh] overflow-y-auto rounded-t-3xl bg-white p-4"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-black">Current Bill · {money(subtotal)}</h2><button onClick={()=>setMobileCart(false)} className="rounded-xl p-2"><X/></button></div>{cart.map(i=><div key={i.id} className="flex items-center gap-3 border-b py-3"><div className="min-w-0 flex-1"><b className="block truncate">{i.name}</b><small className="text-slate-500">{i.quantity} × {money(i.unit_price)}</small></div><b>{money(i.quantity*i.unit_price)}</b></div>)}<div className="mt-5 grid gap-2"><button onClick={()=>{setMobileCart(false);void save('completed')}} disabled={!cart.length||saving} className="min-h-12 rounded-xl bg-emerald-500 font-black text-white">Save & Receive Payment</button><button onClick={()=>{setMobileCart(false);void save('draft')}} disabled={!cart.length||saving} className="min-h-12 rounded-xl border font-bold">Save Draft</button></div></div></div>}
  <PaymentDialog invoiceId={paymentInvoiceId} open={paymentOpen} onClose={()=>setPaymentOpen(false)} onPaymentSaved={()=>void load()}/>
 </div>
}
