'use client'

import { useEffect, useMemo, useState } from 'react'
import { BookOpen, Plus, Search, Users, WalletCards, X } from 'lucide-react'
import toast from 'react-hot-toast'

type Group = { id:string; name:string; code:string; nature:'asset'|'liability'|'income'|'expense'|'equity'; is_system:boolean }
type Account = { id:string; account_group_id:string; account_code:string|null; name:string; account_nature:Group['nature']; party_id:string|null; opening_balance:number; opening_balance_type:'none'|'debit'|'credit'; is_party_account:boolean; is_system:boolean; is_active:boolean }
const natureLabel={asset:'Assets',liability:'Liabilities',income:'Income',expense:'Expenses',equity:'Capital / Equity'}

export default function AccountsPage(){
 const [groups,setGroups]=useState<Group[]>([]); const [accounts,setAccounts]=useState<Account[]>([]); const [search,setSearch]=useState(''); const [group,setGroup]=useState('all'); const [show,setShow]=useState(false); const [loading,setLoading]=useState(true)
 async function load(){setLoading(true);const r=await fetch('/api/accounts',{cache:'no-store'});const j=await r.json().catch(()=>({}));setLoading(false);if(!r.ok)return toast.error(j.error||'Unable to load accounts');setGroups(j.groups||[]);setAccounts(j.accounts||[])}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return accounts.filter(a=>(group==='all'||a.account_group_id===group)&&(!q||`${a.name} ${a.account_code||''}`.toLowerCase().includes(q)))},[accounts,search,group])
 const partyCount=accounts.filter(a=>a.is_party_account).length
 return <div className="mx-auto max-w-7xl space-y-5">
  <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex rounded-full bg-indigo-100 px-3 py-1 text-xs font-bold text-indigo-700">Accounts</span><h1 className="mt-3 text-2xl font-black text-slate-950 sm:text-3xl">Chart of Accounts</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Every ledger account belongs to a group. Parties are accounts too: customers are normally under Sundry Debtors and suppliers under Sundry Creditors, based on their balance direction.</p></div><button onClick={()=>setShow(true)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 text-sm font-bold text-white hover:bg-indigo-700"><Plus className="h-4 w-4"/> New Account</button></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Stat icon={<BookOpen/>} label="Accounts" value={String(accounts.length)}/><Stat icon={<WalletCards/>} label="Groups" value={String(groups.length)}/><Stat icon={<Users/>} label="Party accounts" value={String(partyCount)}/></div></section>
  <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search accounts" className="min-h-11 w-full rounded-xl border px-10 text-sm outline-none focus:border-indigo-500"/></div><select value={group} onChange={e=>setGroup(e.target.value)} className="min-h-11 rounded-xl border px-3 text-sm sm:w-72"><option value="all">All groups</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></div>
   {loading?<div className="p-12 text-center text-sm text-slate-500">Loading accounts…</div>:<div className="divide-y divide-slate-100">{filtered.map(a=>{const g=groups.find(x=>x.id===a.account_group_id);return <div key={a.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-start gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${a.is_party_account?'bg-blue-50 text-blue-700':'bg-slate-50 text-slate-600'}`}>{a.is_party_account?<Users className="h-4 w-4"/>:<WalletCards className="h-4 w-4"/>}</span><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-slate-900">{a.name}</h2>{a.is_party_account&&<span className="rounded-full bg-blue-100 px-2 py-1 text-[10px] font-bold text-blue-700">PARTY</span>}</div><p className="mt-1 text-xs text-slate-500">{a.account_code||'No code'} · {g?.name||'Group'} · {natureLabel[a.account_nature]}</p></div></div><div className="text-left sm:text-right"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Opening balance</p><p className="mt-1 text-sm font-black">{Number(a.opening_balance).toFixed(2)} {a.opening_balance_type==='none'?'':a.opening_balance_type.toUpperCase()}</p></div></div>})}{!filtered.length&&<div className="p-12 text-center text-sm text-slate-500">No accounts found.</div>}</div>}
  </section>{show&&<AccountForm groups={groups} onClose={()=>setShow(false)} onSaved={()=>{setShow(false);void load()}}/>}
 </div>
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-100 text-indigo-700">{icon}</span><div><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-black">{value}</p></div></div>}
function AccountForm({groups,onClose,onSaved}:{groups:Group[];onClose:()=>void;onSaved:()=>void}){const [saving,setSaving]=useState(false);const [f,setF]=useState({group:'',code:'',name:'',balance:'0',balanceType:'none' as 'none'|'debit'|'credit',notes:''});const selected=groups.find(g=>g.id===f.group);function set(k:keyof typeof f,v:string){setF(x=>({...x,[k]:v}))}async function submit(e:React.FormEvent){e.preventDefault();if(!selected)return toast.error('Select a group');setSaving(true);const r=await fetch('/api/accounts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:{account_group_id:f.group,account_code:f.code,name:f.name,account_nature:selected.nature,opening_balance:Number(f.balance||0),opening_balance_type:f.balanceType,notes:f.notes,is_active:true}})});const j=await r.json().catch(()=>({}));setSaving(false);if(!r.ok)return toast.error(j.error||'Unable to create account');toast.success('Account created');onSaved()}
return <div className="fixed inset-0 z-[70] overflow-y-auto bg-slate-950/40 p-4"><div className="mx-auto my-8 max-w-xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-black">New Account</h2><p className="mt-1 text-xs text-slate-500">Choose the balance-sheet / P&L group first.</p></div><button onClick={onClose}><X className="h-5 w-5 text-slate-500"/></button></div><form onSubmit={submit} className="space-y-4 p-5"><label className="block text-sm font-semibold">Account group<select required value={f.group} onChange={e=>set('group',e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"><option value="">Select group</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name} · {natureLabel[g.nature]}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Account name<input required value={f.name} onChange={e=>set('name',e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label className="block text-sm font-semibold">Account code<input value={f.code} onChange={e=>set('code',e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Opening balance<input type="number" min="0" step="0.01" value={f.balance} onChange={e=>set('balance',e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3"/></label><label className="block text-sm font-semibold">Debit / Credit<select value={f.balanceType} onChange={e=>set('balanceType',e.target.value as typeof f.balanceType)} className="mt-1 min-h-11 w-full rounded-xl border px-3"><option value="none">None</option><option value="debit">Debit</option><option value="credit">Credit</option></select></label></div><label className="block text-sm font-semibold">Notes<textarea value={f.notes} onChange={e=>set('notes',e.target.value)} className="mt-1 min-h-24 w-full rounded-xl border p-3"/></label><div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="min-h-11 rounded-xl border px-5 font-semibold">Cancel</button><button disabled={saving} className="min-h-11 rounded-xl bg-indigo-600 px-5 font-bold text-white disabled:opacity-50">{saving?'Saving…':'Create account'}</button></div></form></div></div>}
