'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { Banknote, BarChart3, ChevronRight, CreditCard, RefreshCw, ShoppingCart, WalletCards } from 'lucide-react'

type Day={date:string;sales:number;cashCollections:number;bankCollections:number;totalCollections:number}
type Payment={id:string;receipt_no:string|null;payment_method:'cash'|'bank';amount:number;reference_no:string|null;paid_at:string;status:string;invoice_id:string;party_name:string}
type Report={staff:{name:string;role:string};period:{start:string;end:string};today:Day;totals:{sales:number;cash:number;bank:number;collections:number};daily:Day[];recentPayments:Payment[]}
const money=(n:number)=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`
const dateLabel=(s:string)=>new Date(`${s}T12:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})

export default function StaffDashboard(){
 const [data,setData]=useState<Report|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/dashboard/staff-summary',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load staff dashboard');setData(j)}catch(e){setError(e instanceof Error?e.message:'Unable to load staff dashboard')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const chart=useMemo(()=>data?.daily.slice(-7)??[],[data]); const max=Math.max(1,...chart.map(x=>Math.max(x.sales,x.totalCollections)))
 if(loading)return <div className="rounded-[28px] border border-slate-200 bg-white p-6 shadow-sm"><div className="h-7 w-56 animate-pulse rounded bg-slate-100"/><div className="mt-6 h-72 animate-pulse rounded-3xl bg-slate-50"/></div>
 if(error)return <section className="rounded-[28px] border border-amber-200 bg-amber-50 p-6"><p className="font-bold text-amber-900">Staff dashboard unavailable</p><p className="mt-1 text-sm text-amber-700">{error}</p><button onClick={()=>void load()} className="mt-4 rounded-xl bg-white px-4 py-2 text-sm font-bold text-amber-900 shadow-sm">Try again</button></section>
 if(!data)return null
 const t=data.today
 return <div className="space-y-5">
  <section className="relative overflow-hidden rounded-[30px] border border-emerald-200 bg-gradient-to-br from-emerald-50 via-emerald-100 to-emerald-200 p-5 text-emerald-950 shadow-sm sm:p-7"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-white/60 blur-3xl"/><div className="relative flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><span className="inline-flex rounded-full border border-emerald-200 bg-white/70 px-3 py-1 text-[10px] font-black uppercase tracking-[.18em] text-emerald-800">Staff counter dashboard</span><h1 className="mt-3 text-2xl font-black tracking-tight text-emerald-950 sm:text-3xl">Good day, {data.staff.name || 'Team Member'}</h1><p className="mt-2 text-sm text-emerald-900/75">Track today’s sales and exactly what has been collected in cash and bank.</p></div><button onClick={()=>void load()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-white/80 px-4 text-sm font-bold text-emerald-800 ring-1 ring-emerald-200 hover:bg-white"><RefreshCw className="h-4 w-4"/> Refresh</button></div></section>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<ShoppingCart/>} label="Today's sales" value={t.sales} tone="red"/><Metric icon={<Banknote/>} label="Cash in hand" value={t.cashCollections} tone="green"/><Metric icon={<CreditCard/>} label="Bank collection" value={t.bankCollections} tone="red"/><Metric icon={<WalletCards/>} label="Total collection" value={t.totalCollections} tone="green"/></section>
  <section className="grid gap-5 xl:grid-cols-[1.5fr_.8fr]">
   <section className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-emerald-700"/><h2 className="text-lg font-black">Daily sales & collections</h2></div><p className="mt-1 text-xs text-slate-500">Last 7 days · sales compared with money actually received.</p></div><Link href="/dashboard/sales" className="inline-flex items-center gap-1 text-xs font-bold text-emerald-700">Open POS <ChevronRight className="h-4 w-4"/></Link></div><div className="mt-7 flex h-64 items-end gap-2 overflow-x-auto pb-1">{chart.map(x=><div key={x.date} className="group flex min-w-[52px] flex-1 flex-col items-center justify-end gap-2" title={`${x.date} · Sales ${money(x.sales)} · Cash ${money(x.cashCollections)} · Bank ${money(x.bankCollections)}`}><div className="flex h-48 w-full max-w-[54px] items-end gap-1 rounded-2xl bg-slate-50 p-1"><div className="w-1/2 rounded-t-md bg-rose-300" style={{height:`${Math.max(x.sales?4:1,x.sales/max*100)}%`}}/><div className="w-1/2 rounded-t-md bg-emerald-300" style={{height:`${Math.max(x.totalCollections?4:1,x.totalCollections/max*100)}%`}}/></div><span className="text-[10px] font-semibold text-slate-500">{dateLabel(x.date)}</span></div>)}</div><div className="mt-3 flex flex-wrap items-center gap-4 text-xs font-semibold text-slate-500"><span className="inline-flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-rose-300"/> Sales</span><span className="inline-flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-emerald-300"/> Collections</span><span className="ml-auto">7-day sales <b className="text-slate-900">{money(data.totals.sales)}</b></span></div></section>
   <section className="rounded-[26px] border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-lg font-black">Today's collection split</h2><p className="mt-1 text-xs text-slate-500">Money received against sales invoices.</p><div className="mt-6 space-y-4"><Split label="Cash in hand" value={t.cashCollections} total={Math.max(t.totalCollections,1)} icon={<Banknote/>} tone="green"/><Split label="Bank" value={t.bankCollections} total={Math.max(t.totalCollections,1)} icon={<CreditCard/>} tone="red"/></div><div className="mt-6 rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-emerald-950"><p className="text-xs text-emerald-700">Total collected today</p><p className="mt-1 text-2xl font-black">{money(t.totalCollections)}</p><p className="mt-1 text-[11px] text-emerald-700">Sales today: {money(t.sales)}</p></div></section>
  </section>
  <section className="rounded-[26px] border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="text-lg font-black">Recent collections</h2><p className="mt-1 text-xs text-slate-500">Latest receipts recorded by the POS.</p></div><Link href="/dashboard/sales" className="text-xs font-bold text-emerald-700">New sale</Link></div><div className="divide-y divide-slate-100">{data.recentPayments.length?data.recentPayments.map(p=><div key={p.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div className="flex min-w-0 items-center gap-3"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${p.payment_method==='cash'?'bg-emerald-50 text-emerald-600':'bg-rose-50 text-rose-500'}`}>{p.payment_method==='cash'?<Banknote className="h-5 w-5"/>:<CreditCard className="h-5 w-5"/>}</span><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-900">{p.party_name}</p><p className="truncate text-xs text-slate-500">{p.receipt_no || 'Receipt'} · {new Date(p.paid_at).toLocaleString('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</p></div></div><div className="flex items-center justify-between gap-5 sm:justify-end"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-black uppercase text-slate-600">{p.payment_method}</span><b className="text-base font-black">{money(p.amount)}</b></div></div>):<div className="p-8 text-center text-sm text-slate-500">No collections recorded yet.</div>}</div></section>
 </div>
}

function Metric({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:number;tone:string}){const bg=tone==='green'?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-600';return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${bg}`}>{icon}</span><p className="mt-3 text-[11px] font-black uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-1 text-2xl font-black tracking-tight text-slate-950">{money(value)}</p></div>}
function Split({label,value,total,icon,tone}:{label:string;value:number;total:number;icon:React.ReactNode;tone:'green'|'red'}){return <div><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 font-bold text-slate-700"><span className={tone==='green'?'text-emerald-600':'text-rose-500'}>{icon}</span>{label}</span><b>{money(value)}</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${tone==='green'?'bg-emerald-300':'bg-rose-300'}`} style={{width:`${Math.min(100,value/total*100)}%`}}/></div></div>}
